spring:
  application:
    name: spring-data-demo-1
  datasource:
    username: root
    password: root
    server:
      port: 8088
    url: jdbc:sqlserver://localhost;databaseName=sample;encrypt=false;
    jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
